// Sender 
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>
#include <sys/msg.h>

#define MAX_TEXT 512

// We need to create a structure for sending the message and to decide on type of the message
struct my_msg_st {
    long int my_msg_type; // For message type i.e. from which process to which process
    char some_text[MAX_TEXT];
};

int main() {
    int running = 1;
    struct my_msg_st some_data; // Making an instance of the structure
    int msgid;
    char buffer[BUFSIZ];

    // We need to generate a msgid
    // msgid can be generated by using msgget
    msgid = msgget((key_t)1234, 0666 | IPC_CREAT);

    // if not formed it will give error message
    if (msgid == -1) {
        fprintf(stderr, "msgget failed with error: %d\n", errno);
        exit(EXIT_FAILURE);
    }

    while (running) {
        printf("Enter some text: "); // It will ask you to type the data
        fgets(buffer, BUFSIZ, stdin);

        some_data.my_msg_type = 1; // It is an agreement between the processes
        strcpy(some_data.some_text, buffer); // Reading and appending the message

        // Now we need to send the message
        if (msgsnd(msgid, (void *)&some_data, MAX_TEXT, 0) == -1) {
            fprintf(stderr, "msgsnd failed\n");
            exit(EXIT_FAILURE);
        }

        if (strncmp(buffer, "end", 3) == 0) {
            running = 0;
        }
    }

    exit(EXIT_SUCCESS);
}
